tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "openssl@1.1"
brew "mysql", restart_service: true
brew "ruby-build"
brew "rbenv"
brew "yarn"
cask "wkhtmltopdf"
